service: serverless-js
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
functions:
  application:
    handler: bin/serverless.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/users
          method: get
plugins:
  - serverless-offline
